INSERT INTO magic_the_gathering_cards (
    card_id,
    scryfall_id,
    name,
    set_code,
    set_name,
    rarity,
    mana_cost,
    type_line,
    illustrator,
    is_creature,
    is_instant,
    is_sorcery,
    is_enchantment,
    is_artifact,
    is_land,
    is_planeswalker,
    is_legendary,
    is_saga,
    is_room,
    is_battle,
    is_kindred
)
VALUES
    (
        2001,
        'dummy-scryfall-ltr-lightning-bolt',
        'Lightning Bolt',
        'LTR',
        'The Lord of the Rings: Tales of Middle-earth',
        'uncommon',
        '{R}',
        'Instant',
        'Christopher Rush',
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ),
    (
        2002,
        'dummy-scryfall-m10-lightning-bolt',
        'Lightning Bolt',
        'M10',
        'Magic 2010',
        'common',
        '{R}',
        'Instant',
        'Christopher Moeller',
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ),
    (
        2003,
        'dummy-scryfall-ltr-llanowar-elves',
        'Llanowar Elves',
        'LTR',
        'The Lord of the Rings: Tales of Middle-earth',
        'common',
        '{G}',
        'Creature — Elf Druid',
        'Viko Menezes',
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ),
    (
        2004,
        'dummy-scryfall-dom-llanowar-elves',
        'Llanowar Elves',
        'DOM',
        'Dominaria',
        'common',
        '{G}',
        'Creature — Elf Druid',
        'Chris Rahn',
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    )
ON CONFLICT (scryfall_id)
DO NOTHING;